### ISSUE TITLE
Running styledoc throws error body.innerHTML = "<form></form><form></form>";

### ISSUE THREAD

**Issue by hugogmg** [thybzi/styledoc#1]
whatever I run with styledoc the following error is thrown. Any idea?

/usr/local/lib/node_modules/styledoc/node_modules/jquery/dist/jquery.js:9360
    body.innerHTML = "<form></form><form></form>";
                   ^

TypeError: Cannot set property 'innerHTML' of undefined
    at /usr/local/lib/node_modules/styledoc/node_modules/jquery/dist/jquery.js:9360:17
    at /usr/local/lib/node_modules/styledoc/node_modules/jquery/dist/jquery.js:9362:4
    at module.exports (/usr/local/lib/node_modules/styledoc/node_modules/jquery/dist/jquery.js:31:12)
    at /usr/local/lib/node_modules/styledoc/styledoc.js:85:13
    at MODULE_VERSION (/usr/local/lib/node_modules/styledoc/styledoc.js:33:26)
    at Object.<anonymous> (/usr/local/lib/node_modules/styledoc/styledoc.js:39:2)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)

Thanks

**Comment by thybzi** [comment]
Hello! Sorry for being so long to answer.

For me to investigate this issue, please provide the following information:
- how you run styledoc (cli or js version, parameters, etc)
- which template you're using (default one provided or your own custom)
- what OS and NodeJS version you're using.
